# Generated by Django 2.0.6 on 2018-07-12 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('direction', models.CharField(choices=[('IN', 'Took to nursery'), ('OUT', 'took from nursery')], max_length=3)),
                ('relative', models.CharField(choices=[('M', 'Mother'), ('F', 'Father')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('grade', models.SmallIntegerField()),
                ('is_studying', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='journal',
            name='kid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='journal.Kid'),
        ),
    ]
